name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: ^0.3.4
  firebase_storage: ^2.1.1+2
  firebase_auth: ^0.9.0
  firebase_database: ^2.0.3
  cloud_firestore: ^0.10.0
  search_map_place: ^0.1.1
  progress_dialog: ^1.2.0
  flutter_screenutil: ^0.7.0
  flutter_slidable: "^0.5.4"

 

  animated_text_kit: ^2.0.0
  modal_progress_hud: ^0.1.3
  simple_progress_bar: ^0.0.3
  flutter_animation_progress_bar: ^1.0.0
  flutter_beautiful_popup: ^1.5.0
  carousel_slider: ^1.4.1
  provider: ^4.0.2
  google_maps_flutter: ^0.5.21+17
  geolocator: ^5.2.0
  simple_animations: ^1.3.6
  camera: ^0.5.7+3
  image_cropper: ^1.2.0
  image_picker: ^0.6.3+1
  beauty_textfield: ^0.0.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
